### PR TITLE
Fix window loading time

### PR DESCRIPTION
**Pull request by andela-johia**
#### What does this PR do?
- This PR reduces the window loading time by moving the `ad scripts` from the `head` to the bottom.

#### Description of task completed?
- Move `ad scripts` from the `head` to the `bottom` with other Javascript scripts.

#### Screenshots
screenshot from localhost

### CODE REVIEW

**Comment by DavidLemayian** [comment]
@andela-johia Please add full page screenshot to show if this affects ads loading compared to http://health.the-star.co.ke/

**Comment by andela-johia** [comment]
@DavidLemayian Thanks for the feedback. The PR has been updated with screenshots as requested.

**Comment by DavidLemayian** [comment]
@andela-johia Thanks for this. Let's have full page side by side screenshots of this PR. Use a plugin such as Awesome Screenshot for the full page screenshot instead of just "screen printing".

This will allow inspection of difference if any of this.

**Comment by andela-johia** [comment]
@DavidLemayian I have implemented feedback. The PR has screenshots from the live application and its localhost counterpart after the implementation of the blocking ad scripts

**Comment by DavidLemayian** [comment]
Fixes #14

**Pull request merged**
